# Adopted from https://github.com/docker/metadata-action/tree/v3.3.0#basic
# (Apache License 2.0)
name: GHCR

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  ghcr:
    uses: builderhub/actions/.github/workflows/buildah-build-push-workflow.yaml@v0.1.0-beta.2
    with:
      image: builderhub/buildkit-nix
      tags: ${{ github.sha }}
      containerfiles: ./bootstrap.Dockerfile
      context: .
      registry: ghcr.io
      push: true
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
